language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
install:
    - pip install -r requirements.txt
script:
    - coverage run test.py
    - pytest --cov = CMAutoDiff/
after_success:
    - codecov
